global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nats'
    static_configs:
      - targets: ['nats-exporter:7777']
  - job_name: 'server'
    static_configs:
      - targets: ['host.docker.internal:3000']