apiVersion: v1
kind: Service
metadata:
  name: users-postgres
  labels:
    app: belote
    component: users-postgres
spec:
  type: ClusterIP
  selector:
    app: belote
    component: users-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
