apiVersion: v1
kind: Secret
metadata:
  name: belote-secrets
  labels:
    app: belote
    component: config
stringData:
  POSTGRES_PASSWORD: "admin"
  JWT_SECRET: "replace-me"
  USER_DATABASE_URL: "postgresql://postgres:admin@users-postgres:5432/belote-users"
  LOBBY_DATABASE_URL: "postgresql://postgres:admin@lobbies-postgres:5432/belote-lobbies"
  COSMOS_ENDPOINT: "https://belote-profile-db.documents.azure.com:443/"
