apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: belote
    component: auth-service
spec:
  type: ClusterIP
  selector:
    app: belote
    component: auth-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
