apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/config/application-configmap.yaml
  - ../../base/config/application-secrets.yaml
  - ../../base/client/deployment.yaml
  - ../../base/client/service.yaml
  - ../minikube/ingress.yaml
patches:
  - path: ../minikube/client-service-nodeport.yaml
