apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: belote
    component: client
spec:
  type: ClusterIP
  selector:
    app: belote
    component: client
  ports:
    - name: http
      port: 80
      targetPort: 80
