apiVersion: v1
kind: Service
metadata:
  name: lobbies-postgres
  labels:
    app: belote
    component: lobbies-postgres
spec:
  type: ClusterIP
  selector:
    app: belote
    component: lobbies-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
