apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/config/application-configmap.yaml
  - ../../base/config/application-secrets.yaml
  - ../../base/nats/deployment.yaml
  - ../../base/nats/service.yaml
  - ../../base/server/deployment.yaml
  - ../../base/server/service.yaml
